### ISSUE TITLE
Link to the "smaller" database is broken in your README

### ISSUE THREAD

**Issue by Naville** [mrphrazer/msynth#1]
Title

**Comment by mrphrazer** [comment]
Which link do you mean? I tested all links again, they seem to work for me

**Comment by google-mirror** [comment]
> Which link do you mean? I tested all links again, they seem to work for me

He is blocked by china GFW

**Comment by Naville** [comment]
Hi:
Not really, at the time of posting the link of the smaller db (that was in github) was dead for some reason and gave me the traditional GitHub "Not Found" error page. Probably just some issue on GitHub side
