### ISSUE TITLE
minus operation

### ISSUE THREAD

**Issue by Vulmatch** [mrphrazer/msynth#2]
Excellent work. Just report a minor bug:
 >>>v0=ExprId("v0",32)
 >>>v1=ExprId("v1",32)
 >>> v0=v0-v1
 >>> print(v0)
v0 + -v1
>>> 

------------------------------------------------------------
minus two operands results in "+-"

**Comment by mrphrazer** [comment]
Hi!

Thanks! This is Miasm's expression normalization at work. It might not be intuitive, but semantically correct.
