### ISSUE TITLE
Handling General Obfuscation

### ISSUE THREAD

**Issue by peikexin9** [mrphrazer/msynth#4]
Hi Tim,

Thanks for the effort in releasing such a well-documented tool. I am wondering if msynth can be used to deobfuscate binaries compiled (obfuscated) by llvm-obfuscator? For example, I feed an obfuscated function to msynth, and it outputs a deobfuscated one. Thanks for your attention.

**Comment by mrphrazer** [comment]
Hi Kexin,

msynth works fine for the complex arithmetic expressions introduced by llvm-obfuscator, but it is not an end-to-end deobfuscator. It specializes on the simplification of complex expressions you, for instance, derive via symbolic execution. Let me give you an example:

The script [symbolic_simplification.py](https://github.com/mrphrazer/msynth/blob/main/scripts/symbolic_simplification.py) symbolically executes a single basic block with [Miasm's](https://github.com/cea-sec/miasm) symbolic execution engine and simplifies each derived formula. To simplify a function in an llvm-obfuscator sample, you would have to adapt the SE to follow the whole function (or only execute part of the basic blocks that use complex expressions), extract the relevant expressions and feed them into msynth. [In this repository](https://github.com/mrphrazer/hitb2021ams_deobfuscation) you'll find another example how we can combine Miasm and msynth to actually work on a FinSpy sample protected with OLLVM.

**Comment by mrphrazer** [comment]
I'll close the issue for now. If you have further questions, feel free to re-open it again

**Comment by peikexin9** [comment]
Appreciate the answer, @mrphrazer
